-- Gateway application tables are owned by SQLModel and created during app startup.
-- This file intentionally contains no DDL or seed data.
-- Demo MCP data remains in public (see 01_customers.sql).
